title: Kevin Orta
description: Passionate software engineer and passionate educator with a focus on inspring young minds in computer science. Currently pursuing a B.S. in Computer Science and Information Security at John Jay College of Criminal Justice.
theme: jekyll-theme-minimal
